title: Servicios
icon: list-bullet

tabs:
  content:
    label: Content
    icon: text
    sections:
      parts:
        headline: Secciones
        type: pages
        status: all
        info: "{{ page.intendedTemplate }}"
        image: false
        templates:
          - cover
          - centertext
          - imagetext
          - features
          - squares2
  seo:
    label: SEO
    icon: search
    columns:
      - width: 2/3
        fields:
          meta_title:
            type: text
            label: Meta Title
            help: "El título que aparecerá en los resultados de búsqueda"
          meta_description:
            type: textarea
            label: Meta Description
            help: "Descripción breve para los motores de búsqueda"
          meta_keywords:
            type: tags
            label: Meta Keywords
            help: "Palabras clave separadas por comas"
      - width: 1/3
        fields:
          og_image:
            type: files
            label: Open Graph Image
            max: 1
            help: "Imagen para compartir en redes sociales"